### ISSUE TITLE
issue running WinPCA on GL data

### ISSUE THREAD

**Issue by nerdbrained** [MoritzBlumer/winpca#2]
Hi Moritz - I'm attempting to run WinPCA on a beagle file generated by ANGSD (`winpca pca angsd_depth1_15_notrans_renamed.beagle.gz chr1:1-41082910 chr1 -v GL`) and getting this error:

Traceback (most recent call last):
  File "/opt/winpca/winpca", line 267, in <module>
    main()
  File "/opt/winpca/winpca", line 84, in main
    wpca.window_parser()
  File "/opt/winpca/modules/windowed_pca.py", line 626, in window_parser
    if self.win: self.gl_process_win()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/winpca/modules/windowed_pca.py", line 233, in gl_process_win
    self.gl_min_maf_filter()
  File "/opt/winpca/modules/windowed_pca.py", line 204, in gl_min_maf_filter
    self.gl_min_maf_arr = emMAF(self.w_gl_arr, 200, 1e-4, self.n_threads)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: emMAF() takes 3 positional arguments but 4 were given

...so something is going wrong with emMAF. I am confused about this function - if I just open up Python, import it (`from pcangsd.shared import emMAF`) as it is imported by WinPCA, and then run emMAF() I get: 

emMAF() missing 4 required positional arguments: 'L', 'iter', 'tole', and 't'`.

...so it should be looking for the 4 arguments that WinPCA is supplying. But if I look at the function as defined in the pcangsd repo (`def emMAF(L, iter, tole):`) it looks like it's only taking 3 arguments, which would produce the error that I am getting from WinPCA.

Any ideas? Thank you!

**Comment by nerdbrained** [comment]
This looks like it might be a pcangsd version issue - emMAF in the most recent version (v.1.36.0) takes 3 arguments, while in v.1.2 it takes 4. Will try downgrading to pcangsd v.1.2.

**Comment by nerdbrained** [comment]
Confirmed - it seems like WinPCA will work on a .beagle.gz file if the pcangsd v.1.2 is used, but not if v.1.36.0 is used. We had some difficulty getting the former pcangsd version running so it might still be better to update WinPCA to use the newer version of pcangsd.

**Comment by MoritzBlumer** [comment]
Hi again – thanks a lot for making me aware of this. There was quite some back and forth with the number of arguments emMAF and emPCA expects between different PCAngsd versions, this should now be fixed and work with both 1.2 and 1.36. 

Please let me know if you run into any other issues!
